# Generated by Django 4.1.3 on 2022-12-08 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitpicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitpicture_title', models.CharField(max_length=255)),
                ('fitpicture_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
