# Generated by Django 4.1.3 on 2022-12-08 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
